### ISSUE TITLE
Dashboard needs develoment

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/jakhu#11]
Dashboard files are in views/dashboard. Sass is in views/css/dashboard.scss
We need it to be responsive (works on mobiles, tablet, and PCs without looking awkward).
It must have:
* A hamburger menu :hamburger: :heavy_check_mark:
* A navbar to jump to places on screen
* Notifications area
* Stats
* Ability to start, stop and restart web-apps/tubs

**Comment by ksambhi** [comment]
There is an in progress dashboard (needs developing)

**Comment by ksambhi** [comment]
Pull request: #36

**Comment by ksambhi** [comment]
On hold

**Comment by ksambhi** [comment]
Moved to #41
